In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import cohen_kappa_score

In [ ]:
abstract_df = pd.read_excel("../../supplemental_materials/phase1_withN.xlsx", header=1)
fulltext_df = pd.read_excel("../../supplemental_materials/phase2_withN.xlsx", header=1)

In [3]:
abstract_df.head()

,Author,Publication Year,Title,Abstract,Majdi's Vote to Include,Comments/Justification,RECHECK NOTE,Nataly's Vote to Include,Agreement Metric,DOI
0,"Huegli, David; Chavaillaz, Alain; Sauer, Juerg...",2025,Effects of false alarms and miscues of decisio...,ABSTRACT Decision support systems such as exp...,True,Evaluates AI-supported human decisions in safe...,NaN,True,NaN,10.1080/00140139.2025.2453546
1,"Fleury, Emmanuelle; Pignol, Jean Philippe; Kil...",2025,Stereotactic radiation therapy or protons for ...,"Purpose\nFor ocular melanoma, selecting betwee...",True,AI supports treatment selection between SRT an...,NaN,True,NaN,10.1016/j.ijrobp.2025.06.3867
2,"Khan, Ehsan; Lambrakis, Kristina; Briffa, Tom;...",2025,Re-engineering the clinical approach to suspec...,Background\nClinical work-up for suspected car...,True,AI supports cardiac ED decisions and is compar...,NaN,False,NaN,10.1016/j.ahj.2025.02.016
3,"Gutierrez-Zaballa, Jon; Basterretxea, Koldo; E...",2024,Evaluating single event upsets in deep neural ...,As the deployment of artificial intelligence (...,False,Tests DNN robustness for image segmentation wi...,NaN,False,NaN,10.1016/j.sysarc.2024.103242
4,"Silvey, Scott; Patel, Nilang; Liu, Jinze; Tafa...",2024,A machine learning algorithm avoids unnecessar...,Background & Aims\nDespite the poor prognosis ...,False,ML informs whether paracentesis is needed and ...,"No decision-making, just modeling of safety-cr...",False,NaN,10.1016/j.cgh.2024.06.015

In [4]:
abstract_k = cohen_kappa_score(abstract_df["Majdi\'s Vote to Include"], abstract_df["Nataly\'s Vote to Include"])
print(f"Title/Abstract Cohen's Kappa: {abstract_k}")

Title/Abstract Cohen's Kappa: 0.4716981132075472

In [5]:
fulltext_df.head()

,Author,Publication Year,Title,Majdi's Vote to Include,Brief Justification,Nataly's Vote to Include,Nataly's Justification,DOI
0,"Bucker, Michael; Hoti, Kreshnik; Rose, Olaf",2024,Artificial intelligence to assist decision-mak...,True,The study uses decision trees as its final AI ...,True,Highlights need for interpretable models and h...,10.1016/j.rcsop.2024.100491
1,"Metta, Carlo; Beretta, Andrea; Guidotti, Ricca...",2024,Advancing dermatological diagnostics: Interpre...,True,"It evaluates human diagnostic classification,...",True,the interpretability and explainability aspect...,10.3390/diagnostics14070753
2,"Goodall, Noah J.",2021,Comparison of automated vehicle struck-from-be...,True,it satisfies all most core requirements: human...,True,"This is an older study, and really just an ana...",10.1016/j.aap.2021.106056
3,"Pang, Bizhao; Hu, Xinting; Dai, Wei; Low, Kin ...",2024,Stochastic route optimization under dynamic gr...,False,even though the application is highly safety-...,False,this is heavily focused on optimizing routes a...,10.1016/j.tre.2024.103717
4,"Kieu, Anh Mai; Dang, Ha Nguyet; Tran, Khanh Th...",2024,Development and validation of machine learning...,True,This is a particularly strong match because it...,True,highlights interpretability of a decision tree...,10.29090/psa.2024.04.24.AP0713

In [6]:
full_k = cohen_kappa_score(fulltext_df["Majdi\'s Vote to Include"], fulltext_df["Nataly\'s Vote to Include"])
print(f"Full Text Cohen's Kappa: {full_k}")

Full Text Cohen's Kappa: 0.4642857142857143